# Generated by Django 4.2 on 2023-06-27 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=profile_app.models.profile_avatar_dir_path,
                        verbose_name="avatar",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="description"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullName",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="full_name"
                    ),
                ),
                ("email", models.EmailField(max_length=200, verbose_name="email")),
                (
                    "registration_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="registration_time"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "BEGINNER"),
                            ("silver", "SILVER"),
                            ("gold", "GOLD"),
                            ("platinum", "PLATINUM"),
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(blank=True, null=True, verbose_name="balance"),
                ),
                (
                    "avatar",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_app.avatar",
                        verbose_name="avatar",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "ordering": ["user"],
            },
        ),
    ]
