# Generated by Django 4.2 on 2023-06-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profile_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="avatar",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="avatar",
                to="profile_app.profile",
            ),
        ),
    ]
