# Generated by Django 4.2 on 2023-06-27 15:57

from django.db import migrations, models
import django.db.models.deletion
import shop_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile_app", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="description"
                    ),
                ),
                (
                    "fullDescription",
                    models.TextField(
                        blank=True, null=True, verbose_name="full description"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="price"
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="archived"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop_app.models.product_preview_dir_path,
                        verbose_name="preview",
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="quantity")),
                (
                    "freeDelivery",
                    models.BooleanField(default=False, verbose_name="delivery"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="date"
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["title", "price"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="shop_app.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategories",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="tag")),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
            },
        ),
        migrations.CreateModel(
            name="SubCategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        upload_to=shop_app.models.sub_category_image_dir_path,
                        verbose_name="image",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="description"
                    ),
                ),
                (
                    "subcategory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="shop_app.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salePrice",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="sale"
                    ),
                ),
                (
                    "dateFrom",
                    models.DateField(blank=True, null=True, verbose_name="date_from"),
                ),
                (
                    "dateTo",
                    models.DateField(blank=True, null=True, verbose_name="date_to"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale",
                        to="shop_app.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                ("text", models.TextField(blank=True, verbose_name="description")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="date"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="rating"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to="profile_app.profile",
                        verbose_name="user_id",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="shop_app.product",
                        verbose_name="product_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        upload_to=shop_app.models.prod_image_dir_path,
                        verbose_name="image",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="description"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop_app.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop_app.productcategory",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="shop_app.tag", verbose_name="tag"),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="city")),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_time"
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        choices=[("online", "ONLINE"), ("cash", "CASH")],
                        default="cash",
                        max_length=50,
                        verbose_name="payment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unfinished", "Unfinished"),
                            ("paid", "Paid"),
                            ("collected", "Collected"),
                            ("delivered", "Delivered"),
                        ],
                        default=None,
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "deliveryType",
                    models.CharField(
                        choices=[("free", "FREE"), ("paid ", "PAID")],
                        default=None,
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="orders",
                        to="shop_app.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_app.profile",
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CatagoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        upload_to=shop_app.models.category_image_dir_path
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=250)),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="shop_app.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
    ]
