# Generated by Django 4.2 on 2023-06-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=False, verbose_name="available"),
        ),
    ]
