# Generated by Django 4.2 on 2023-07-03 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profile_app", "0002_remove_profile_avatar_avatar_profile"),
        ("shop_app", "0003_specification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="profile_app.profile",
                verbose_name="user_id",
            ),
        ),
    ]
