# Generated by Django 4.2 on 2023-07-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0004_alter_review_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unfinished", "Unfinished"),
                    ("paid", "Paid"),
                    ("collected", "Collected"),
                    ("delivered", "Delivered"),
                ],
                default=0,
                max_length=30,
                verbose_name="status",
            ),
        ),
    ]
