# Generated by Django 4.2 on 2023-07-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0008_orderproductcount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproductcount",
            old_name="count",
            new_name="count_product",
        ),
        migrations.AlterField(
            model_name="orderproductcount",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_products",
                to="shop_app.product",
            ),
        ),
    ]
