# Generated by Django 4.2 on 2023-07-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0009_rename_count_orderproductcount_count_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.CharField(
                choices=[("true", "true"), ("false ", "false")],
                default="true",
                max_length=30,
                null=True,
            ),
        ),
    ]
