# Generated by Django 4.2 on 2023-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0012_alter_order_deliverytype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(
                choices=[("ordinary", "ordinary"), ("express ", "express")],
                default="ordinary",
                max_length=30,
                null=True,
            ),
        ),
    ]
